local ucs_mapping = {
    AIRBlow = {category = "AIR", subcategory = "BLOW"},
    AIRBrst = {category = "AIR", subcategory = "BURST"},
    AIRHiss = {category = "AIR", subcategory = "HISS"},
    AIRMisc = {category = "AIR", subcategory = "MISC"},
    AIRSuck = {category = "AIR", subcategory = "SUCTION"},
    AERODoor = {category = "AIRCRAFT", subcategory = "DOOR"},
    AEROHeli = {category = "AIRCRAFT", subcategory = "HELICOPTER"},
    AEROInt = {category = "AIRCRAFT", subcategory = "INTERIOR"},
    AEROJet = {category = "AIRCRAFT", subcategory = "JET"},
    AEROMech = {category = "AIRCRAFT", subcategory = "MECHANISM"},
    AEROMil = {category = "AIRCRAFT", subcategory = "MILITARY"},
    AEROMisc = {category = "AIRCRAFT", subcategory = "MISC"},
    AEROProp = {category = "AIRCRAFT", subcategory = "PROP"},
    AERORadio = {category = "AIRCRAFT", subcategory = "RADIO CONTROLLED"},
    AERORckt = {category = "AIRCRAFT", subcategory = "ROCKET"},
    ALRMBell = {category = "ALARMS", subcategory = "BELL"},
    ALRMBuzr = {category = "ALARMS", subcategory = "BUZZER"},
    ALRMClok = {category = "ALARMS", subcategory = "CLOCK"},
    ALRMElec = {category = "ALARMS", subcategory = "ELECTRONIC"},
    ALRMMisc = {category = "ALARMS", subcategory = "MISC"},
    ALRMSirn = {category = "ALARMS", subcategory = "SIREN"},
    AMBAir = {category = "AMBIENCE", subcategory = "AIR"},
    AMBAlpn = {category = "AMBIENCE", subcategory = "ALPINE"},
    AMBAmus = {category = "AMBIENCE", subcategory = "AMUSEMENT"},
    AMBBird = {category = "AMBIENCE", subcategory = "BIRDSONG"},
    AMBCele = {category = "AMBIENCE", subcategory = "CELEBRATION"},
    AMBCnst = {category = "AMBIENCE", subcategory = "CONSTRUCTION"},
    AMBDsrt = {category = "AMBIENCE", subcategory = "DESERT"},
    AMBDsgn = {category = "AMBIENCE", subcategory = "DESIGNED"},
    AMBEmrg = {category = "AMBIENCE", subcategory = "EMERGENCY"},
    AMBFant = {category = "AMBIENCE", subcategory = "FANTASY"},
    AMBFarm = {category = "AMBIENCE", subcategory = "FARM"},
    AMBForst = {category = "AMBIENCE", subcategory = "FOREST"},
    AMBGras = {category = "AMBIENCE", subcategory = "GRASSLAND"},
    AMBHist = {category = "AMBIENCE", subcategory = "HISTORICAL"},
    AMBTech = {category = "AMBIENCE", subcategory = "HITECH"},
    AMBHosp = {category = "AMBIENCE", subcategory = "HOSPITAL"},
    AMBInd = {category = "AMBIENCE", subcategory = "INDUSTRIAL"},
    AMBInsc = {category = "AMBIENCE", subcategory = "INSECT"},
    AMBLake = {category = "AMBIENCE", subcategory = "LAKESIDE"},
    AMBMrkt = {category = "AMBIENCE", subcategory = "MARKET"},
    AMBMisc = {category = "AMBIENCE", subcategory = "MISC"},
    AMBNaut = {category = "AMBIENCE", subcategory = "NAUTICAL"},
    AMBOffc = {category = "AMBIENCE", subcategory = "OFFICE"},
    AMBPark = {category = "AMBIENCE", subcategory = "PARK"},
    AMBPrisn = {category = "AMBIENCE", subcategory = "PRISON"},
    AMBPrtst = {category = "AMBIENCE", subcategory = "PROTEST"},
    AMBPubl = {category = "AMBIENCE", subcategory = "PUBLIC PLACE"},
    AMBRlgn = {category = "AMBIENCE", subcategory = "RELIGIOUS"},
    AMBHome = {category = "AMBIENCE", subcategory = "RESIDENTIAL"},
    AMBRest = {category = "AMBIENCE", subcategory = "RESTAURANT & BAR"},
    AMBRoom = {category = "AMBIENCE", subcategory = "ROOM TONE"},
    AMBRurl = {category = "AMBIENCE", subcategory = "RURAL"},
    AMBSchl = {category = "AMBIENCE", subcategory = "SCHOOL"},
    AMBSci = {category = "AMBIENCE", subcategory = "SCIFI"},
    AMBSea = {category = "AMBIENCE", subcategory = "SEASIDE"},
    AMBSprt = {category = "AMBIENCE", subcategory = "SPORT"},
    AMBSubn = {category = "AMBIENCE", subcategory = "SUBURBAN"},
    AMBSwmp = {category = "AMBIENCE", subcategory = "SWAMP"},
    AMBTown = {category = "AMBIENCE", subcategory = "TOWN"},
    AMBTraf = {category = "AMBIENCE", subcategory = "TRAFFIC"},
    AMBTran = {category = "AMBIENCE", subcategory = "TRANSPORTATION"},
    AMBTrop = {category = "AMBIENCE", subcategory = "TROPICAL"},
    AMBTndra = {category = "AMBIENCE", subcategory = "TUNDRA"},
    AMBUndr = {category = "AMBIENCE", subcategory = "UNDERGROUND"},
    AMBUndwtr = {category = "AMBIENCE", subcategory = "UNDERWATER"},
    AMBUrbn = {category = "AMBIENCE", subcategory = "URBAN"},
    AMBWar = {category = "AMBIENCE", subcategory = "WARFARE"},
    ANMLAmph = {category = "ANIMALS", subcategory = "AMPHIBIAN"},
    ANMLAqua = {category = "ANIMALS", subcategory = "AQUATIC"},
    ANMLBat = {category = "ANIMALS", subcategory = "BAT"},
    ANMLCat = {category = "ANIMALS", subcategory = "CAT DOMESTIC"},
    ANMLWcat = {category = "ANIMALS", subcategory = "CAT WILD"},
    ANMLDog = {category = "ANIMALS", subcategory = "DOG"},
    ANMLWdog = {category = "ANIMALS", subcategory = "DOG WILD"},
    ANMLFarm = {category = "ANIMALS", subcategory = "FARM"},
    ANMLHors = {category = "ANIMALS", subcategory = "HORSE"},
    ANMLInsc = {category = "ANIMALS", subcategory = "INSECT"},
    ANMLMisc = {category = "ANIMALS", subcategory = "MISC"},
    ANMLPrim = {category = "ANIMALS", subcategory = "PRIMATE"},
    ANMLRept = {category = "ANIMALS", subcategory = "REPTILE"},
    ANMLRdnt = {category = "ANIMALS", subcategory = "RODENT"},
    ANMLWild = {category = "ANIMALS", subcategory = "WILD"},
    ADR = {category = "ARCHIVED", subcategory = "ADR"},
    ASSET = {category = "ARCHIVED", subcategory = "ASSET"},
    BNCE = {category = "ARCHIVED", subcategory = "BOUNCE"},
    IR = {category = "ARCHIVED", subcategory = "IMPULSE RESPONSE"},
    LPGRP = {category = "ARCHIVED", subcategory = "LOOP GROUP"},
    MIX = {category = "ARCHIVED", subcategory = "MIX"},
    PFX = {category = "ARCHIVED", subcategory = "PFX"},
    PROD = {category = "ARCHIVED", subcategory = "PRODUCTION"},
    RAW = {category = "ARCHIVED", subcategory = "RAW"},
    REF = {category = "ARCHIVED", subcategory = "REFERENCE"},
    SCNE = {category = "ARCHIVED", subcategory = "SCENE"},
    TEST = {category = "ARCHIVED", subcategory = "TEST TONE"},
    TMARK = {category = "ARCHIVED", subcategory = "TRADEMARKED"},
    WIP = {category = "ARCHIVED", subcategory = "WORK IN PROGRESS"},
    WTF = {category = "ARCHIVED", subcategory = "WTF"},
    BEEPAppl = {category = "BEEPS", subcategory = "APPLIANCE"},
    BEEP = {category = "BEEPS", subcategory = "GENERAL"},
    BEEPLofi = {category = "BEEPS", subcategory = "LOFI"},
    BEEPMed = {category = "BEEPS", subcategory = "MEDICAL"},
    BEEPTimer = {category = "BEEPS", subcategory = "TIMER"},
    BEEPVeh = {category = "BEEPS", subcategory = "VEHICLE"},
    BELLAnml = {category = "BELLS", subcategory = "ANIMAL"},
    BELLDoor = {category = "BELLS", subcategory = "DOORBELL"},
    BELLGong = {category = "BELLS", subcategory = "GONG"},
    BELLHand = {category = "BELLS", subcategory = "HANDBELL"},
    BELLLrg = {category = "BELLS", subcategory = "LARGE"},
    BELLMisc = {category = "BELLS", subcategory = "MISC"},
    BIRDPrey = {category = "BIRDS", subcategory = "BIRD OF PREY"},
    BIRDCrow = {category = "BIRDS", subcategory = "CROW"},
    BIRDFowl = {category = "BIRDS", subcategory = "FOWL"},
    BIRDMisc = {category = "BIRDS", subcategory = "MISC"},
    BIRDSea = {category = "BIRDS", subcategory = "SEA"},
    BIRDSong = {category = "BIRDS", subcategory = "SONGBIRD"},
    BIRDTrop = {category = "BIRDS", subcategory = "TROPICAL"},
    BIRDWade = {category = "BIRDS", subcategory = "WADING"},
    BOATAir = {category = "BOATS", subcategory = "AIR BOAT"},
    BOATWash = {category = "BOATS", subcategory = "BOW WASH"},
    BOATDoor = {category = "BOATS", subcategory = "DOOR"},
    BOATElec = {category = "BOATS", subcategory = "ELECTRIC"},
    BOATFish = {category = "BOATS", subcategory = "FISHING"},
    BOATHorn = {category = "BOATS", subcategory = "HORN"},
    BOATInt = {category = "BOATS", subcategory = "INTERIOR"},
    BOATMech = {category = "BOATS", subcategory = "MECHANISM"},
    BOATMil = {category = "BOATS", subcategory = "MILITARY"},
    BOATMisc = {category = "BOATS", subcategory = "MISC"},
    BOATMotr = {category = "BOATS", subcategory = "MOTORBOAT"},
    BOATRace = {category = "BOATS", subcategory = "RACING"},
    BOATRow = {category = "BOATS", subcategory = "ROWBOAT"},
    BOATSail = {category = "BOATS", subcategory = "SAILBOAT"},
    BOATShip = {category = "BOATS", subcategory = "SHIP"},
    BOATStm = {category = "BOATS", subcategory = "STEAM"},
    BOATSub = {category = "BOATS", subcategory = "SUBMARINE"},
    BOATUndwtr = {category = "BOATS", subcategory = "UNDERWATER"},
    BLLTBy = {category = "BULLETS", subcategory = "BY"},
    BLLTImpt = {category = "BULLETS", subcategory = "IMPACT"},
    BLLTMisc = {category = "BULLETS", subcategory = "MISC"},
    BLLTRico = {category = "BULLETS", subcategory = "RICOCHET"},
    BLLTShel = {category = "BULLETS", subcategory = "SHELL"},
    TOONAnml = {category = "CARTOON", subcategory = "ANIMAL"},
    TOONBoing = {category = "CARTOON", subcategory = "BOING"},
    TOONClang = {category = "CARTOON", subcategory = "CLANG"},
    TOONCreak = {category = "CARTOON", subcategory = "CREAK"},
    TOONHorn = {category = "CARTOON", subcategory = "HORN"},
    TOONImpt = {category = "CARTOON", subcategory = "IMPACT"},
    TOONMach = {category = "CARTOON", subcategory = "MACHINE"},
    TOONMisc = {category = "CARTOON", subcategory = "MISC"},
    TOONMx = {category = "CARTOON", subcategory = "MUSICAL"},
    TOONPluk = {category = "CARTOON", subcategory = "PLUCK"},
    TOONPop = {category = "CARTOON", subcategory = "POP"},
    TOONShake = {category = "CARTOON", subcategory = "SHAKE"},
    TOONSplt = {category = "CARTOON", subcategory = "SPLAT"},
    TOONSqk = {category = "CARTOON", subcategory = "SQUEAK"},
    TOONStrch = {category = "CARTOON", subcategory = "STRETCH"},
    TOONSwsh = {category = "CARTOON", subcategory = "SWISH"},
    TOONTwang = {category = "CARTOON", subcategory = "TWANG"},
    TOONVeh = {category = "CARTOON", subcategory = "VEHICLE"},
    TOONVox = {category = "CARTOON", subcategory = "VOCAL"},
    TOONWarb = {category = "CARTOON", subcategory = "WARBLE"},
    TOONWhis = {category = "CARTOON", subcategory = "WHISTLE"},
    TOONZip = {category = "CARTOON", subcategory = "ZIP"},
    CERMBrk = {category = "CERAMICS", subcategory = "BREAK"},
    CERMCrsh = {category = "CERAMICS", subcategory = "CRASH & DEBRIS"},
    CERMFric = {category = "CERAMICS", subcategory = "FRICTION"},
    CERMHndl = {category = "CERAMICS", subcategory = "HANDLE"},
    CERMImpt = {category = "CERAMICS", subcategory = "IMPACT"},
    CERMMisc = {category = "CERAMICS", subcategory = "MISC"},
    CERMMvmt = {category = "CERAMICS", subcategory = "MOVEMENT"},
    CERMTonl = {category = "CERAMICS", subcategory = "TONAL"},
    CHAINBrk = {category = "CHAINS", subcategory = "BREAK"},
    CHAINHndl = {category = "CHAINS", subcategory = "HANDLE"},
    CHAINImpt = {category = "CHAINS", subcategory = "IMPACT"},
    CHAINMisc = {category = "CHAINS", subcategory = "MISC"},
    CHAINMvmt = {category = "CHAINS", subcategory = "MOVEMENT"},
    CHEMAcid = {category = "CHEMICALS", subcategory = "ACID"},
    CHEMMisc = {category = "CHEMICALS", subcategory = "MISC"},
    CHEMReac = {category = "CHEMICALS", subcategory = "REACTION"},
    CLOCKChim = {category = "CLOCKS", subcategory = "CHIME"},
    CLOCKMech = {category = "CLOCKS", subcategory = "MECHANICS"},
    CLOCKMisc = {category = "CLOCKS", subcategory = "MISC"},
    CLOCKTick = {category = "CLOCKS", subcategory = "TICK"},
    CLOTHFlp = {category = "CLOTH", subcategory = "FLAP"},
    CLOTHHndl = {category = "CLOTH", subcategory = "HANDLE"},
    CLOTHImpt = {category = "CLOTH", subcategory = "IMPACT"},
    CLOTHMisc = {category = "CLOTH", subcategory = "MISC"},
    CLOTHMvmt = {category = "CLOTH", subcategory = "MOVEMENT"},
    CLOTHRip = {category = "CLOTH", subcategory = "RIP"},
    COMAv = {category = "COMMUNICATIONS", subcategory = "AUDIO VISUAL"},
    COMCam = {category = "COMMUNICATIONS", subcategory = "CAMERA"},
    COMCell = {category = "COMMUNICATIONS", subcategory = "CELLPHONE"},
    COMMic = {category = "COMMUNICATIONS", subcategory = "MICROPHONE"},
    COMMisc = {category = "COMMUNICATIONS", subcategory = "MISC"},
    COMPhono = {category = "COMMUNICATIONS", subcategory = "PHONOGRAPH"},
    COMRadio = {category = "COMMUNICATIONS", subcategory = "RADIO"},
    COMStatic = {category = "COMMUNICATIONS", subcategory = "STATIC"},
    COMTelm = {category = "COMMUNICATIONS", subcategory = "TELEMETRY"},
    COMTelph = {category = "COMMUNICATIONS", subcategory = "TELEPHONE"},
    COMTv = {category = "COMMUNICATIONS", subcategory = "TELEVISION"},
    COMTran = {category = "COMMUNICATIONS", subcategory = "TRANSCEIVER"},
    COMType = {category = "COMMUNICATIONS", subcategory = "TYPEWRITER"},
    CMPTDriv = {category = "COMPUTERS", subcategory = "HARD DRIVE"},
    CMPTKey = {category = "COMPUTERS", subcategory = "KEYBOARD & MOUSE"},
    CMPTMisc = {category = "COMPUTERS", subcategory = "MISC"},
    CREAAqua = {category = "CREATURES", subcategory = "AQUATIC"},
    CREAAvian = {category = "CREATURES", subcategory = "AVIAN"},
    CREABeast = {category = "CREATURES", subcategory = "BEAST"},
    CREABlob = {category = "CREATURES", subcategory = "BLOB"},
    CREADino = {category = "CREATURES", subcategory = "DINOSAUR"},
    CREADrgn = {category = "CREATURES", subcategory = "DRAGON"},
    CREAElem = {category = "CREATURES", subcategory = "ELEMENTAL"},
    CREAEthr = {category = "CREATURES", subcategory = "ETHEREAL"},
    CREAHmn = {category = "CREATURES", subcategory = "HUMANOID"},
    CREAInsc = {category = "CREATURES", subcategory = "INSECTOID"},
    CREAMisc = {category = "CREATURES", subcategory = "MISC"},
    CREAMnstr = {category = "CREATURES", subcategory = "MONSTER"},
    CREARept = {category = "CREATURES", subcategory = "REPTILIAN"},
    CREASmall = {category = "CREATURES", subcategory = "SMALL"},
    CREASrce = {category = "CREATURES", subcategory = "SOURCE"},
    CRWDAngr = {category = "CROWDS", subcategory = "ANGRY"},
    CRWDApls = {category = "CROWDS", subcategory = "APPLAUSE"},
    CRWDBatl = {category = "CROWDS", subcategory = "BATTLE"},
    CRWDCele = {category = "CROWDS", subcategory = "CELEBRATION"},
    CRWDCheer = {category = "CROWDS", subcategory = "CHEERING"},
    CRWDChld = {category = "CROWDS", subcategory = "CHILDREN"},
    CRWDConv = {category = "CROWDS", subcategory = "CONVERSATION"},
    CRWDLaff = {category = "CROWDS", subcategory = "LAUGHTER"},
    CRWDLoop = {category = "CROWDS", subcategory = "LOOP GROUP"},
    CRWDMisc = {category = "CROWDS", subcategory = "MISC"},
    CRWDPanic = {category = "CROWDS", subcategory = "PANIC"},
    CRWDQuiet = {category = "CROWDS", subcategory = "QUIET"},
    CRWDReac = {category = "CROWDS", subcategory = "REACTION"},
    CRWDSing = {category = "CROWDS", subcategory = "SINGING"},
    CRWDSprt = {category = "CROWDS", subcategory = "SPORT"},
    CRWDWalla = {category = "CROWDS", subcategory = "WALLA"},
    DSGNBass = {category = "DESIGNED", subcategory = "BASS DIVE"},
    DSGNBoom = {category = "DESIGNED", subcategory = "BOOM"},
    DSGNBram = {category = "DESIGNED", subcategory = "BRAAM"},
    DSGNDist = {category = "DESIGNED", subcategory = "DISTORTION"},
    DSGNDron = {category = "DESIGNED", subcategory = "DRONE"},
    DSGNErie = {category = "DESIGNED", subcategory = "EERIE"},
    DSGNEthr = {category = "DESIGNED", subcategory = "ETHEREAL"},
    DSGNGran = {category = "DESIGNED", subcategory = "GRANULAR"},
    DSGNImpt = {category = "DESIGNED", subcategory = "IMPACT"},
    DSGNMisc = {category = "DESIGNED", subcategory = "MISC"},
    DSGNMorph = {category = "DESIGNED", subcategory = "MORPH"},
    DSGNRise = {category = "DESIGNED", subcategory = "RISER"},
    DSGNRmbl = {category = "DESIGNED", subcategory = "RUMBLE"},
    DSGNRythm = {category = "DESIGNED", subcategory = "RHYTHMIC"},
    DSGNSrce = {category = "DESIGNED", subcategory = "SOURCE"},
    DSGNStngr = {category = "DESIGNED", subcategory = "STINGER"},
    DSGNSynth = {category = "DESIGNED", subcategory = "SYNTHETIC"},
    DSGNTonl = {category = "DESIGNED", subcategory = "TONAL"},
    DSGNVocl = {category = "DESIGNED", subcategory = "VOCAL"},
    DSGNWhsh = {category = "DESIGNED", subcategory = "WHOOSH"},
    DESTRClpse = {category = "DESTRUCTION", subcategory = "COLLAPSE"},
    DESTRCrsh = {category = "DESTRUCTION", subcategory = "CRASH & DEBRIS"},
    DESTRMisc = {category = "DESTRUCTION", subcategory = "MISC"},
    DIRTCrsh = {category = "DIRT & SAND", subcategory = "CRASH & DEBRIS"},
    DIRTDust = {category = "DIRT & SAND", subcategory = "DUST"},
    DIRTHndl = {category = "DIRT & SAND", subcategory = "HANDLE"},
    DIRTImpt = {category = "DIRT & SAND", subcategory = "IMPACT"},
    DIRTMisc = {category = "DIRT & SAND", subcategory = "MISC"},
    DIRTMvmt = {category = "DIRT & SAND", subcategory = "MOVEMENT"},
    DIRTTonl = {category = "DIRT & SAND", subcategory = "TONAL"},
    DOORAntq = {category = "DOORS", subcategory = "ANTIQUE"},
    DOORAppl = {category = "DOORS", subcategory = "APPLIANCE"},
    DOORCab = {category = "DOORS", subcategory = "CABINET"},
    DOORComp = {category = "DOORS", subcategory = "COMPOSITE"},
    DOORCreak = {category = "DOORS", subcategory = "CREAK"},
    DOORDungn = {category = "DOORS", subcategory = "DUNGEON"},
    DOORElec = {category = "DOORS", subcategory = "ELECTRIC"},
    DOORGate = {category = "DOORS", subcategory = "GATE"},
    DOORGlas = {category = "DOORS", subcategory = "GLASS"},
    DOORHdwr = {category = "DOORS", subcategory = "HARDWARE"},
    DOORTech = {category = "DOORS", subcategory = "HITECH"},
    DOORHydr = {category = "DOORS", subcategory = "HYDRAULIC & PNEUMATIC"},
    DOORKnck = {category = "DOORS", subcategory = "KNOCK"},
    DOORMetl = {category = "DOORS", subcategory = "METAL"},
    DOORMisc = {category = "DOORS", subcategory = "MISC"},
    DOORPlas = {category = "DOORS", subcategory = "PLASTIC"},
    DOORPrisn = {category = "DOORS", subcategory = "PRISON"},
    DOORRevl = {category = "DOORS", subcategory = "REVOLVING"},
    DOORSlid = {category = "DOORS", subcategory = "SLIDING"},
    DOORSton = {category = "DOORS", subcategory = "STONE"},
    DOORSwng = {category = "DOORS", subcategory = "SWINGING"},
    DOORWood = {category = "DOORS", subcategory = "WOOD"},
    DRWRMetl = {category = "DRAWERS", subcategory = "METAL"},
    DRWRMisc = {category = "DRAWERS", subcategory = "MISC"},
    DRWRPlas = {category = "DRAWERS", subcategory = "PLASTIC"},
    DRWRWood = {category = "DRAWERS", subcategory = "WOOD"},
    ELECArc = {category = "ELECTRICITY", subcategory = "ARC"},
    ELECBuzz = {category = "ELECTRICITY", subcategory = "BUZZ & HUM"},
    ELECEmf = {category = "ELECTRICITY", subcategory = "ELECTROMAGNETIC"},
    ELECMisc = {category = "ELECTRICITY", subcategory = "MISC"},
    ELECSprk = {category = "ELECTRICITY", subcategory = "SPARKS"},
    ELECZap = {category = "ELECTRICITY", subcategory = "ZAP"},
    EQUIPBridle = {category = "EQUIPMENT", subcategory = "BRIDLE & TACK"},
    EQUIPTech = {category = "EQUIPMENT", subcategory = "HITECH"},
    EQUIPMisc = {category = "EQUIPMENT", subcategory = "MISC"},
    EQUIPRec = {category = "EQUIPMENT", subcategory = "RECREATIONAL"},
    EQUIPSprt = {category = "EQUIPMENT", subcategory = "SPORT"},
    EQUIPTact = {category = "EQUIPMENT", subcategory = "TACTICAL"},
    EXPLDsgn = {category = "EXPLOSIONS", subcategory = "DESIGNED"},
    EXPLMisc = {category = "EXPLOSIONS", subcategory = "MISC"},
    EXPLReal = {category = "EXPLOSIONS", subcategory = "REAL"},
    FARTDsgn = {category = "FARTS", subcategory = "DESIGNED"},
    FARTMisc = {category = "FARTS", subcategory = "MISC"},
    FARTReal = {category = "FARTS", subcategory = "REAL"},
    FGHTBf = {category = "FIGHT", subcategory = "BODYFALL"},
    FGHTClth = {category = "FIGHT", subcategory = "CLOTH"},
    FGHTGrab = {category = "FIGHT", subcategory = "GRAB"},
    FGHTImpt = {category = "FIGHT", subcategory = "IMPACT"},
    FGHTMisc = {category = "FIGHT", subcategory = "MISC"},
    FIREBurn = {category = "FIRE", subcategory = "BURNING"},
    FIREBrst = {category = "FIRE", subcategory = "BURST"},
    FIRECrkl = {category = "FIRE", subcategory = "CRACKLE"},
    FIREGas = {category = "FIRE", subcategory = "GAS"},
    FIREIgn = {category = "FIRE", subcategory = "IGNITE"},
    FIREMisc = {category = "FIRE", subcategory = "MISC"},
    FIRESizz = {category = "FIRE", subcategory = "SIZZLE"},
    FIRETrch = {category = "FIRE", subcategory = "TORCH"},
    FIRETurb = {category = "FIRE", subcategory = "TURBULENT"},
    FIREWhsh = {category = "FIRE", subcategory = "WHOOSH"},
    FRWKComr = {category = "FIREWORKS", subcategory = "COMMERCIAL"},
    FRWKMisc = {category = "FIREWORKS", subcategory = "MISC"},
    FRWKRec = {category = "FIREWORKS", subcategory = "RECREATIONAL"},
    FOLYClth = {category = "FOLEY", subcategory = "CLOTH"},
    FOLYFeet = {category = "FOLEY", subcategory = "FEET"},
    FOLYHand = {category = "FOLEY", subcategory = "HANDS"},
    FOLYMisc = {category = "FOLEY", subcategory = "MISC"},
    FOLYProp = {category = "FOLEY", subcategory = "PROP"},
    FOODCook = {category = "FOOD & DRINK", subcategory = "COOKING"},
    FOODDrnk = {category = "FOOD & DRINK", subcategory = "DRINKING"},
    FOODEat = {category = "FOOD & DRINK", subcategory = "EATING"},
    FOODGware = {category = "FOOD & DRINK", subcategory = "GLASSWARE"},
    FOODIngr = {category = "FOOD & DRINK", subcategory = "INGREDIENTS"},
    FOODKware = {category = "FOOD & DRINK", subcategory = "KITCHENWARE"},
    FOODMisc = {category = "FOOD & DRINK", subcategory = "MISC"},
    FOODPour = {category = "FOOD & DRINK", subcategory = "POUR"},
    FOODTware = {category = "FOOD & DRINK", subcategory = "TABLEWARE"},
    FEETAnml = {category = "FOOTSTEPS", subcategory = "ANIMAL"},
    FEETCrea = {category = "FOOTSTEPS", subcategory = "CREATURE"},
    FEETHors = {category = "FOOTSTEPS", subcategory = "HORSE"},
    FEETHmn = {category = "FOOTSTEPS", subcategory = "HUMAN"},
    FEETMisc = {category = "FOOTSTEPS", subcategory = "MISC"},
    GAMEArcd = {category = "GAMES", subcategory = "ARCADE"},
    GAMEBoard = {category = "GAMES", subcategory = "BOARD"},
    GAMECas = {category = "GAMES", subcategory = "CASINO"},
    GAMEMisc = {category = "GAMES", subcategory = "MISC"},
    GAMEVideo = {category = "GAMES", subcategory = "VIDEO"},
    GEOFuma = {category = "GEOTHERMAL", subcategory = "FUMAROLE"},
    GEOGeyser = {category = "GEOTHERMAL", subcategory = "GEYSER"},
    GEOLava = {category = "GEOTHERMAL", subcategory = "LAVA"},
    GEOMisc = {category = "GEOTHERMAL", subcategory = "MISC"},
    GEOMudpot = {category = "GEOTHERMAL", subcategory = "MUD POTS"},
    GLASBrk = {category = "GLASS", subcategory = "BREAK"},
    GLASCrsh = {category = "GLASS", subcategory = "CRASH & DEBRIS"},
    GLASFric = {category = "GLASS", subcategory = "FRICTION"},
    GLASHndl = {category = "GLASS", subcategory = "HANDLE"},
    GLASImpt = {category = "GLASS", subcategory = "IMPACT"},
    GLASMisc = {category = "GLASS", subcategory = "MISC"},
    GLASMvmt = {category = "GLASS", subcategory = "MOVEMENT"},
    GLASTonl = {category = "GLASS", subcategory = "TONAL"},
    GOREBlood = {category = "GORE", subcategory = "BLOOD"},
    GOREBone = {category = "GORE", subcategory = "BONE"},
    GOREBurn = {category = "GORE", subcategory = "BURN"},
    GOREFlsh = {category = "GORE", subcategory = "FLESH"},
    GOREMisc = {category = "GORE", subcategory = "MISC"},
    GOREOoze = {category = "GORE", subcategory = "OOZE"},
    GORESrce = {category = "GORE", subcategory = "SOURCE"},
    GORESplt = {category = "GORE", subcategory = "SPLAT"},
    GORESqsh = {category = "GORE", subcategory = "SQUISH"},
    GOREStab = {category = "GORE", subcategory = "STAB"},
    GUNAntq = {category = "GUNS", subcategory = "ANTIQUE"},
    GUNArtl = {category = "GUNS", subcategory = "ARTILLERY"},
    GUNAuto = {category = "GUNS", subcategory = "AUTOMATIC"},
    GUNCano = {category = "GUNS", subcategory = "CANNON"},
    GUNHndl = {category = "GUNS", subcategory = "HANDLE"},
    GUNTech = {category = "GUNS", subcategory = "HITECH"},
    GUNMech = {category = "GUNS", subcategory = "MECHANISM"},
    GUNMisc = {category = "GUNS", subcategory = "MISC"},
    GUNPis = {category = "GUNS", subcategory = "PISTOL"},
    GUNRif = {category = "GUNS", subcategory = "RIFLE"},
    GUNShotg = {category = "GUNS", subcategory = "SHOTGUN"},
    GUNSupr = {category = "GUNS", subcategory = "SUPPRESSED"},
    HORNAir = {category = "HORNS", subcategory = "AIR POWERED"},
    HORNCele = {category = "HORNS", subcategory = "CELEBRATION"},
    HORNMisc = {category = "HORNS", subcategory = "MISC"},
    HORNTrad = {category = "HORNS", subcategory = "TRADITIONAL"},
    HMNBlow = {category = "HUMAN", subcategory = "BLOW"},
    HMNBrth = {category = "HUMAN", subcategory = "BREATH"},
    HMNBurp = {category = "HUMAN", subcategory = "BURP"},
    HMNCough = {category = "HUMAN", subcategory = "COUGH"},
    HMNHart = {category = "HUMAN", subcategory = "HEARTBEAT"},
    HMNKiss = {category = "HUMAN", subcategory = "KISS"},
    HMNMisc = {category = "HUMAN", subcategory = "MISC"},
    HMNPee = {category = "HUMAN", subcategory = "PEE"},
    HMNSkin = {category = "HUMAN", subcategory = "SKIN"},
    HMNSneez = {category = "HUMAN", subcategory = "SNEEZE"},
    HMNSniff = {category = "HUMAN", subcategory = "SNIFF"},
    HMNSnor = {category = "HUMAN", subcategory = "SNORE"},
    HMNSpit = {category = "HUMAN", subcategory = "SPIT"},
    HMNVomit = {category = "HUMAN", subcategory = "VOMIT"},
    ICEBrk = {category = "ICE", subcategory = "BREAK"},
    ICECrsh = {category = "ICE", subcategory = "CRASH & DEBRIS"},
    ICEFric = {category = "ICE", subcategory = "FRICTION"},
    ICEHndl = {category = "ICE", subcategory = "HANDLE"},
    ICEImpt = {category = "ICE", subcategory = "IMPACT"},
    ICEMisc = {category = "ICE", subcategory = "MISC"},
    ICEMvmt = {category = "ICE", subcategory = "MOVEMENT"},
    ICETonl = {category = "ICE", subcategory = "TONAL"},
    LASRBeam = {category = "LASERS", subcategory = "BEAM"},
    LASRGun = {category = "LASERS", subcategory = "GUN"},
    LASRImpt = {category = "LASERS", subcategory = "IMPACT"},
    LASRMisc = {category = "LASERS", subcategory = "MISC"},
    LETHRCreak = {category = "LEATHER", subcategory = "CREAK"},
    LETHRHndl = {category = "LEATHER", subcategory = "HANDLE"},
    LETHRImpt = {category = "LEATHER", subcategory = "IMPACT"},
    LETHRMisc = {category = "LEATHER", subcategory = "MISC"},
    LETHRMvmt = {category = "LEATHER", subcategory = "MOVEMENT"},
    LIQBubl = {category = "LIQUID & MUD", subcategory = "BUBBLES"},
    LIQImpt = {category = "LIQUID & MUD", subcategory = "IMPACT"},
    LIQMisc = {category = "LIQUID & MUD", subcategory = "MISC"},
    LIQMvmt = {category = "LIQUID & MUD", subcategory = "MOVEMENT"},
    LIQSuct = {category = "LIQUID & MUD", subcategory = "SUCTION"},
    MACHAmus = {category = "MACHINES", subcategory = "AMUSEMENT"},
    MACHAntq = {category = "MACHINES", subcategory = "ANTIQUE"},
    MACHAppl = {category = "MACHINES", subcategory = "APPLIANCE"},
    MACHCnst = {category = "MACHINES", subcategory = "CONSTRUCTION"},
    MACHElev = {category = "MACHINES", subcategory = "ELEVATOR"},
    MACHEscl = {category = "MACHINES", subcategory = "ESCALATOR"},
    MACHFan = {category = "MACHINES", subcategory = "FAN"},
    MACHGrdn = {category = "MACHINES", subcategory = "GARDEN"},
    MACHGym = {category = "MACHINES", subcategory = "GYM"},
    MACHTech = {category = "MACHINES", subcategory = "HITECH"},
    MACHHvac = {category = "MACHINES", subcategory = "HVAC"},
    MACHInd = {category = "MACHINES", subcategory = "INDUSTRIAL"},
    MACHMech = {category = "MACHINES", subcategory = "MECHANISM"},
    MACHMed = {category = "MACHINES", subcategory = "MEDICAL"},
    MACHMisc = {category = "MACHINES", subcategory = "MISC"},
    MACHOffc = {category = "MACHINES", subcategory = "OFFICE"},
    MACHPump = {category = "MACHINES", subcategory = "PUMP"},
    MAGAngl = {category = "MAGIC", subcategory = "ANGELIC"},
    MAGElem = {category = "MAGIC", subcategory = "ELEMENTAL"},
    MAGEvil = {category = "MAGIC", subcategory = "EVIL"},
    MAGMisc = {category = "MAGIC", subcategory = "MISC"},
    MAGPoof = {category = "MAGIC", subcategory = "POOF"},
    MAGShim = {category = "MAGIC", subcategory = "SHIMMER"},
    MAGSpel = {category = "MAGIC", subcategory = "SPELL"},
    MECHClik = {category = "MECHANICAL", subcategory = "CLICK"},
    MECHGear = {category = "MECHANICAL", subcategory = "GEARS"},
    MECHHydr = {category = "MECHANICAL", subcategory = "HYDRAULIC & PNEUMATIC"},
    MECHLtch = {category = "MECHANICAL", subcategory = "LATCH"},
    MECHLvr = {category = "MECHANICAL", subcategory = "LEVER"},
    MECHLock = {category = "MECHANICAL", subcategory = "LOCK"},
    MECHMisc = {category = "MECHANICAL", subcategory = "MISC"},
    MECHPuly = {category = "MECHANICAL", subcategory = "PULLEY"},
    MECHRtch = {category = "MECHANICAL", subcategory = "RATCHET"},
    MECHRelay = {category = "MECHANICAL", subcategory = "RELAY"},
    MECHRolr = {category = "MECHANICAL", subcategory = "ROLLER"},
    MECHSwtch = {category = "MECHANICAL", subcategory = "SWITCH"},
    METLBrk = {category = "METAL", subcategory = "BREAK"},
    METLCrsh = {category = "METAL", subcategory = "CRASH & DEBRIS"},
    METLFric = {category = "METAL", subcategory = "FRICTION"},
    METLHndl = {category = "METAL", subcategory = "HANDLE"},
    METLImpt = {category = "METAL", subcategory = "IMPACT"},
    METLMisc = {category = "METAL", subcategory = "MISC"},
    METLMvmt = {category = "METAL", subcategory = "MOVEMENT"},
    METLTonl = {category = "METAL", subcategory = "TONAL"},
    MOTRAntq = {category = "MOTORS", subcategory = "ANTIQUE"},
    MOTRComb = {category = "MOTORS", subcategory = "COMBUSTION"},
    MOTRElec = {category = "MOTORS", subcategory = "ELECTRIC"},
    MOTRMisc = {category = "MOTORS", subcategory = "MISC"},
    MOTRSrvo = {category = "MOTORS", subcategory = "SERVO"},
    MOTRTurb = {category = "MOTORS", subcategory = "TURBINE"},
    MOVEActv = {category = "MOVEMENT", subcategory = "ACTIVITY"},
    MOVEAnml = {category = "MOVEMENT", subcategory = "ANIMAL"},
    MOVECrea = {category = "MOVEMENT", subcategory = "CREATURE"},
    MOVECrwd = {category = "MOVEMENT", subcategory = "CROWD"},
    MOVEHmn = {category = "MOVEMENT", subcategory = "HUMAN"},
    MOVEInsc = {category = "MOVEMENT", subcategory = "INSECT"},
    MOVEMisc = {category = "MOVEMENT", subcategory = "MISC"},
    MOVEPres = {category = "MOVEMENT", subcategory = "PRESENCE"},
    MUSCBell = {category = "MUSICAL", subcategory = "BELLS"},
    MUSCBrass = {category = "MUSICAL", subcategory = "BRASS"},
    MUSCChim = {category = "MUSICAL", subcategory = "CHIME"},
    MUSCChor = {category = "MUSICAL", subcategory = "CHORAL"},
    MUSCExpr = {category = "MUSICAL", subcategory = "EXPERIMENTAL"},
    MUSCInst = {category = "MUSICAL", subcategory = "INSTRUMENT"},
    MUSCKeyd = {category = "MUSICAL", subcategory = "KEYED"},
    MUSCLoop = {category = "MUSICAL", subcategory = "LOOP"},
    MUSCMisc = {category = "MUSICAL", subcategory = "MISC"},
    MUSCPerc = {category = "MUSICAL", subcategory = "PERCUSSION"},
    MUSCTnprc = {category = "MUSICAL", subcategory = "PERCUSSION TUNED"},
    MUSCPrfm = {category = "MUSICAL", subcategory = "PERFORMANCE"},
    MUSCPluck = {category = "MUSICAL", subcategory = "PLUCKED"},
    MUSCSmpl = {category = "MUSICAL", subcategory = "SAMPLE"},
    MUSCShake = {category = "MUSICAL", subcategory = "SHAKEN"},
    MUSCSong = {category = "MUSICAL", subcategory = "SONG & PHRASE"},
    MUSCStngr = {category = "MUSICAL", subcategory = "STINGER"},
    MUSCStr = {category = "MUSICAL", subcategory = "STRINGED"},
    MUSCSynth = {category = "MUSICAL", subcategory = "SYNTHESIZED"},
    MUSCToy = {category = "MUSICAL", subcategory = "TOY"},
    MUSCWind = {category = "MUSICAL", subcategory = "WOODWIND"},
    NATDAval = {category = "NATURAL DISASTER", subcategory = "AVALANCHE"},
    NATDQuak = {category = "NATURAL DISASTER", subcategory = "EARTHQUAKE"},
    NATDMisc = {category = "NATURAL DISASTER", subcategory = "MISC"},
    NATDTorn = {category = "NATURAL DISASTER", subcategory = "TORNADO"},
    NATDTsun = {category = "NATURAL DISASTER", subcategory = "TSUNAMI"},
    NATDThyp = {category = "NATURAL DISASTER", subcategory = "TYPHOON"},
    NATDVolc = {category = "NATURAL DISASTER", subcategory = "VOLCANO"},
    OBJBag = {category = "OBJECTS", subcategory = "BAG"},
    OBJBook = {category = "OBJECTS", subcategory = "BOOK"},
    OBJCoin = {category = "OBJECTS", subcategory = "COIN"},
    OBJCont = {category = "OBJECTS", subcategory = "CONTAINER"},
    OBJFash = {category = "OBJECTS", subcategory = "FASHION"},
    OBJFurn = {category = "OBJECTS", subcategory = "FURNITURE"},
    OBJGrdn = {category = "OBJECTS", subcategory = "GARDEN"},
    OBJGym = {category = "OBJECTS", subcategory = "GYM"},
    OBJHsehld = {category = "OBJECTS", subcategory = "HOUSEHOLD"},
    OBJJewl = {category = "OBJECTS", subcategory = "JEWELRY"},
    OBJKey = {category = "OBJECTS", subcategory = "KEYS"},
    OBJLug = {category = "OBJECTS", subcategory = "LUGGAGE"},
    OBJMed = {category = "OBJECTS", subcategory = "MEDICAL"},
    OBJMisc = {category = "OBJECTS", subcategory = "MISC"},
    OBJOffc = {category = "OBJECTS", subcategory = "OFFICE"},
    OBJPack = {category = "OBJECTS", subcategory = "PACKAGING"},
    OBJTape = {category = "OBJECTS", subcategory = "TAPE"},
    OBJUmbr = {category = "OBJECTS", subcategory = "UMBRELLA"},
    OBJWhled = {category = "OBJECTS", subcategory = "WHEELED"},
    OBJWrite = {category = "OBJECTS", subcategory = "WRITING"},
    OBJZipr = {category = "OBJECTS", subcategory = "ZIPPER"},
    PAPRFltr = {category = "PAPER", subcategory = "FLUTTER"},
    PAPRFric = {category = "PAPER", subcategory = "FRICTION"},
    PAPRHndl = {category = "PAPER", subcategory = "HANDLE"},
    PAPRImpt = {category = "PAPER", subcategory = "IMPACT"},
    PAPRMisc = {category = "PAPER", subcategory = "MISC"},
    PAPRRip = {category = "PAPER", subcategory = "RIP"},
    PAPRTonl = {category = "PAPER", subcategory = "TONAL"},
    PLASBrk = {category = "PLASTIC", subcategory = "BREAK"},
    PLASCrsh = {category = "PLASTIC", subcategory = "CRASH & DEBRIS"},
    PLASFric = {category = "PLASTIC", subcategory = "FRICTION"},
    PLASHndl = {category = "PLASTIC", subcategory = "HANDLE"},
    PLASImpt = {category = "PLASTIC", subcategory = "IMPACT"},
    PLASMisc = {category = "PLASTIC", subcategory = "MISC"},
    PLASMvmt = {category = "PLASTIC", subcategory = "MOVEMENT"},
    PLASTonl = {category = "PLASTIC", subcategory = "TONAL"},
    RAINClth = {category = "RAIN", subcategory = "CLOTH"},
    RAINConc = {category = "RAIN", subcategory = "CONCRETE"},
    RAIN = {category = "RAIN", subcategory = "GENERAL"},
    RAINGlas = {category = "RAIN", subcategory = "GLASS"},
    RAINInt = {category = "RAIN", subcategory = "INTERIOR"},
    RAINMetl = {category = "RAIN", subcategory = "METAL"},
    RAINPlas = {category = "RAIN", subcategory = "PLASTIC"},
    RAINVege = {category = "RAIN", subcategory = "VEGETATION"},
    RAINWatr = {category = "RAIN", subcategory = "WATER"},
    RAINWood = {category = "RAIN", subcategory = "WOOD"},
    ROBTMisc = {category = "ROBOTS", subcategory = "MISC"},
    ROBTMvmt = {category = "ROBOTS", subcategory = "MOVEMENT"},
    ROBTVox = {category = "ROBOTS", subcategory = "VOCAL"},
    ROCKBrk = {category = "ROCKS", subcategory = "BREAK"},
    ROCKCrsh = {category = "ROCKS", subcategory = "CRASH & DEBRIS"},
    ROCKFric = {category = "ROCKS", subcategory = "FRICTION"},
    ROCKHndl = {category = "ROCKS", subcategory = "HANDLE"},
    ROCKImpt = {category = "ROCKS", subcategory = "IMPACT"},
    ROCKMisc = {category = "ROCKS", subcategory = "MISC"},
    ROCKMvmt = {category = "ROCKS", subcategory = "MOVEMENT"},
    ROCKTonl = {category = "ROCKS", subcategory = "TONAL"},
    ROPECreak = {category = "ROPE", subcategory = "CREAK"},
    ROPEHndl = {category = "ROPE", subcategory = "HANDLE"},
    ROPEImpt = {category = "ROPE", subcategory = "IMPACT"},
    ROPEMisc = {category = "ROPE", subcategory = "MISC"},
    ROPEMvmt = {category = "ROPE", subcategory = "MOVEMENT"},
    RUBRCrsh = {category = "RUBBER", subcategory = "CRASH & DEBRIS"},
    RUBRFric = {category = "RUBBER", subcategory = "FRICTION"},
    RUBRHndl = {category = "RUBBER", subcategory = "HANDLE"},
    RUBRImpt = {category = "RUBBER", subcategory = "IMPACT"},
    RUBRMisc = {category = "RUBBER", subcategory = "MISC"},
    RUBRMvmt = {category = "RUBBER", subcategory = "MOVEMENT"},
    RUBRTonl = {category = "RUBBER", subcategory = "TONAL"},
    SCIAlrm = {category = "SCIFI", subcategory = "ALARM"},
    SCICmpt = {category = "SCIFI", subcategory = "COMPUTER"},
    SCIDoor = {category = "SCIFI", subcategory = "DOOR"},
    SCIEnrg = {category = "SCIFI", subcategory = "ENERGY"},
    SCIImpt = {category = "SCIFI", subcategory = "IMPACT"},
    SCIMach = {category = "SCIFI", subcategory = "MACHINE"},
    SCIMech = {category = "SCIFI", subcategory = "MECHANISM"},
    SCIMisc = {category = "SCIFI", subcategory = "MISC"},
    SCIRetro = {category = "SCIFI", subcategory = "RETRO"},
    SCIShip = {category = "SCIFI", subcategory = "SPACESHIP"},
    SCIVeh = {category = "SCIFI", subcategory = "VEHICLE"},
    SCIWeap = {category = "SCIFI", subcategory = "WEAPON"},
    SNOWCrsh = {category = "SNOW", subcategory = "CRASH & DEBRIS"},
    SNOWFric = {category = "SNOW", subcategory = "FRICTION"},
    SNOWHndl = {category = "SNOW", subcategory = "HANDLE"},
    SNOWImpt = {category = "SNOW", subcategory = "IMPACT"},
    SNOWMisc = {category = "SNOW", subcategory = "MISC"},
    SNOWMvmt = {category = "SNOW", subcategory = "MOVEMENT"},
    SPRTCourt = {category = "SPORTS", subcategory = "COURT"},
    SPRTField = {category = "SPORTS", subcategory = "FIELD"},
    SPRTGym = {category = "SPORTS", subcategory = "GYM"},
    SPRTIndor = {category = "SPORTS", subcategory = "INDOOR"},
    SPRTMisc = {category = "SPORTS", subcategory = "MISC"},
    SPRTSkate = {category = "SPORTS", subcategory = "SKATE"},
    SPRTTrck = {category = "SPORTS", subcategory = "TRACK & FIELD"},
    SPRTWatr = {category = "SPORTS", subcategory = "WATER"},
    SPRTWntr = {category = "SPORTS", subcategory = "WINTER"},
    SWSH = {category = "SWOOSHES", subcategory = "SWISH"},
    WHSH = {category = "SWOOSHES", subcategory = "WHOOSH"},
    TOOLGrdn = {category = "TOOLS", subcategory = "GARDEN"},
    TOOLHand = {category = "TOOLS", subcategory = "HAND"},
    TOOLMisc = {category = "TOOLS", subcategory = "MISC"},
    TOOLPneu = {category = "TOOLS", subcategory = "PNEUMATIC"},
    TOOLPowr = {category = "TOOLS", subcategory = "POWER"},
    TOYElec = {category = "TOYS", subcategory = "ELECTRONIC"},
    TOYMech = {category = "TOYS", subcategory = "MECHANICAL"},
    TOYMisc = {category = "TOYS", subcategory = "MISC"},
    TRNBrake = {category = "TRAINS", subcategory = "BRAKE"},
    TRNClak = {category = "TRAINS", subcategory = "CLACK"},
    TRNDoor = {category = "TRAINS", subcategory = "DOOR"},
    TRNDiesl = {category = "TRAINS", subcategory = "DIESEL"},
    TRNElec = {category = "TRAINS", subcategory = "ELECTRIC"},
    TRNHspd = {category = "TRAINS", subcategory = "HIGH SPEED"},
    TRNHorn = {category = "TRAINS", subcategory = "HORN"},
    TRNInt = {category = "TRAINS", subcategory = "INTERIOR"},
    TRNMech = {category = "TRAINS", subcategory = "MECHANISM"},
    TRNMisc = {category = "TRAINS", subcategory = "MISC"},
    TRNSteam = {category = "TRAINS", subcategory = "STEAM"},
    TRNSbwy = {category = "TRAINS", subcategory = "SUBWAY"},
    TRNTram = {category = "TRAINS", subcategory = "TRAM"},
    UIAlert = {category = "USER INTERFACE", subcategory = "ALERT"},
    UIBeep = {category = "USER INTERFACE", subcategory = "BEEP"},
    UIClick = {category = "USER INTERFACE", subcategory = "CLICK"},
    UIData = {category = "USER INTERFACE", subcategory = "DATA"},
    UIGlitch = {category = "USER INTERFACE", subcategory = "GLITCH"},
    UIMisc = {category = "USER INTERFACE", subcategory = "MISC"},
    UIMvmt = {category = "USER INTERFACE", subcategory = "MOTION"},
    VEGEGras = {category = "VEGETATION", subcategory = "GRASS"},
    VEGELeaf = {category = "VEGETATION", subcategory = "LEAVES"},
    VEGEMisc = {category = "VEGETATION", subcategory = "MISC"},
    VEGETree = {category = "VEGETATION", subcategory = "TREE"},
    VEHAlrm = {category = "VEHICLES", subcategory = "ALARM"},
    VEHAntq = {category = "VEHICLES", subcategory = "ANTIQUE"},
    VEHAtv = {category = "VEHICLES", subcategory = "ATV"},
    VEHBike = {category = "VEHICLES", subcategory = "BICYCLE"},
    VEHBrake = {category = "VEHICLES", subcategory = "BRAKE"},
    VEHBus = {category = "VEHICLES", subcategory = "BUS"},
    VEHCar = {category = "VEHICLES", subcategory = "CAR"},
    VEHCnst = {category = "VEHICLES", subcategory = "CONSTRUCTION"},
    VEHDoor = {category = "VEHICLES", subcategory = "DOOR"},
    VEHElec = {category = "VEHICLES", subcategory = "ELECTRIC"},
    VEHEmrg = {category = "VEHICLES", subcategory = "EMERGENCY"},
    VEHFarm = {category = "VEHICLES", subcategory = "FARM"},
    VEHFrght = {category = "VEHICLES", subcategory = "FREIGHT"},
    VEHBy = {category = "VEHICLES", subcategory = "GENERIC BY"},
    VEHHorn = {category = "VEHICLES", subcategory = "HORN"},
    VEHInt = {category = "VEHICLES", subcategory = "INTERIOR"},
    VEHJalop = {category = "VEHICLES", subcategory = "JALOPY"},
    VEHMech = {category = "VEHICLES", subcategory = "MECHANISM"},
    VEHMil = {category = "VEHICLES", subcategory = "MILITARY"},
    VEHMisc = {category = "VEHICLES", subcategory = "MISC"},
    VEHMoto = {category = "VEHICLES", subcategory = "MOTORCYCLE"},
    VEHRace = {category = "VEHICLES", subcategory = "RACING"},
    VEHSirn = {category = "VEHICLES", subcategory = "SIREN"},
    VEHSkid = {category = "VEHICLES", subcategory = "SKID"},
    VEHSusp = {category = "VEHICLES", subcategory = "SUSPENSION"},
    VEHTire = {category = "VEHICLES", subcategory = "TIRE"},
    VEHTruck = {category = "VEHICLES", subcategory = "TRUCK VAN & SUV"},
    VEHUtil = {category = "VEHICLES", subcategory = "UTILITY"},
    VEHWagn = {category = "VEHICLES", subcategory = "WAGON"},
    VEHWndw = {category = "VEHICLES", subcategory = "WINDOW"},
    VOXAlien = {category = "VOICES", subcategory = "ALIEN"},
    VOXBaby = {category = "VOICES", subcategory = "BABY"},
    VOXCheer = {category = "VOICES", subcategory = "CHEER"},
    VOXChld = {category = "VOICES", subcategory = "CHILD"},
    VOXCry = {category = "VOICES", subcategory = "CRYING"},
    VOXEfrt = {category = "VOICES", subcategory = "EFFORTS"},
    VOXFem = {category = "VOICES", subcategory = "FEMALE"},
    VOXFutz = {category = "VOICES", subcategory = "FUTZED"},
    VOXHist = {category = "VOICES", subcategory = "HISTORICAL"},
    VOXLaff = {category = "VOICES", subcategory = "LAUGH"},
    VOXMale = {category = "VOICES", subcategory = "MALE"},
    VOXMisc = {category = "VOICES", subcategory = "MISC"},
    VOXReac = {category = "VOICES", subcategory = "REACTION"},
    VOXScrm = {category = "VOICES", subcategory = "SCREAM"},
    VOXSing = {category = "VOICES", subcategory = "SINGING"},
    VOXWhsp = {category = "VOICES", subcategory = "WHISPER"},
    WATRBubl = {category = "WATER", subcategory = "BUBBLES"},
    WATRDran = {category = "WATER", subcategory = "DRAIN"},
    WATRDrip = {category = "WATER", subcategory = "DRIP"},
    WATRFizz = {category = "WATER", subcategory = "FIZZ"},
    WATRFlow = {category = "WATER", subcategory = "FLOW"},
    WATRFoun = {category = "WATER", subcategory = "FOUNTAIN"},
    WATRImpt = {category = "WATER", subcategory = "IMPACT"},
    WATRLap = {category = "WATER", subcategory = "LAP"},
    WATRMisc = {category = "WATER", subcategory = "MISC"},
    WATRMvmt = {category = "WATER", subcategory = "MOVEMENT"},
    WATRPlmb = {category = "WATER", subcategory = "PLUMBING"},
    WATRPour = {category = "WATER", subcategory = "POUR"},
    WATRSplsh = {category = "WATER", subcategory = "SPLASH"},
    WATRSpray = {category = "WATER", subcategory = "SPRAY"},
    WATRStm = {category = "WATER", subcategory = "STEAM"},
    WATRSurf = {category = "WATER", subcategory = "SURF"},
    WATRTurb = {category = "WATER", subcategory = "TURBULENT"},
    WATRUndwtr = {category = "WATER", subcategory = "UNDERWATER"},
    WATRFall = {category = "WATER", subcategory = "WATERFALL"},
    WATRWave = {category = "WATER", subcategory = "WAVE"},
    WEAPArmr = {category = "WEAPONS", subcategory = "ARMOR"},
    WEAPArro = {category = "WEAPONS", subcategory = "ARROW"},
    WEAPAxe = {category = "WEAPONS", subcategory = "AXE"},
    WEAPBlnt = {category = "WEAPONS", subcategory = "BLUNT"},
    WEAPBow = {category = "WEAPONS", subcategory = "BOW"},
    WEAPKnif = {category = "WEAPONS", subcategory = "KNIFE"},
    WEAPMisc = {category = "WEAPONS", subcategory = "MISC"},
    WEAPPole = {category = "WEAPONS", subcategory = "POLEARM"},
    WEAPSiege = {category = "WEAPONS", subcategory = "SIEGE"},
    WEAPSwrd = {category = "WEAPONS", subcategory = "SWORD"},
    WEAPWhip = {category = "WEAPONS", subcategory = "WHIP"},
    HAIL = {category = "WEATHER", subcategory = "HAIL"},
    WTHR = {category = "WEATHER", subcategory = "MISC"},
    STORM = {category = "WEATHER", subcategory = "STORM"},
    THUN = {category = "WEATHER", subcategory = "THUNDER"},
    WHSTHmn = {category = "WHISTLES", subcategory = "HUMAN"},
    WHSTMech = {category = "WHISTLES", subcategory = "MECHANICAL"},
    WHSTMisc = {category = "WHISTLES", subcategory = "MISC"},
    WINDDsgn = {category = "WIND", subcategory = "DESIGNED"},
    WIND = {category = "WIND", subcategory = "GENERAL"},
    WINDGust = {category = "WIND", subcategory = "GUST"},
    WINDInt = {category = "WIND", subcategory = "INTERIOR"},
    WINDTonl = {category = "WIND", subcategory = "TONAL"},
    WINDTurb = {category = "WIND", subcategory = "TURBULENT"},
    WINDVege = {category = "WIND", subcategory = "VEGETATION"},
    WNDWCover = {category = "WINDOWS", subcategory = "COVERING"},
    WNDWHdwr = {category = "WINDOWS", subcategory = "HARDWARE"},
    WNDWKnck = {category = "WINDOWS", subcategory = "KNOCK"},
    WNDWMetl = {category = "WINDOWS", subcategory = "METAL"},
    WNDWMisc = {category = "WINDOWS", subcategory = "MISC"},
    WNDWPlas = {category = "WINDOWS", subcategory = "PLASTIC"},
    WNDWWood = {category = "WINDOWS", subcategory = "WOOD"},
    WINGBird = {category = "WINGS", subcategory = "BIRD"},
    WINGCrea = {category = "WINGS", subcategory = "CREATURE"},
    WINGInsc = {category = "WINGS", subcategory = "INSECT"},
    WINGMisc = {category = "WINGS", subcategory = "MISC"},
    WOODBrk = {category = "WOOD", subcategory = "BREAK"},
    WOODCrsh = {category = "WOOD", subcategory = "CRASH & DEBRIS"},
    WOODFric = {category = "WOOD", subcategory = "FRICTION"},
    WOODHndl = {category = "WOOD", subcategory = "HANDLE"},
    WOODImpt = {category = "WOOD", subcategory = "IMPACT"},
    WOODMisc = {category = "WOOD", subcategory = "MISC"},
    WOODMvmt = {category = "WOOD", subcategory = "MOVEMENT"},
    WOODTonl = {category = "WOOD", subcategory = "TONAL"},
}

function Main()
    reaper.ShowConsoleMsg("Starting media processing...\n")
    
    local title = reaper.JS_Localize("Media Explorer", "common")
    local hWnd = reaper.JS_Window_Find(title, true)
    if not hWnd then return end
    
    local file_LV = reaper.JS_Window_FindChildByID(hWnd, 0x3E9)
    local sel_count = reaper.JS_ListView_GetItemCount(file_LV)
    reaper.ShowConsoleMsg("Found " .. sel_count .. " items\n")
    
    local combo = reaper.JS_Window_FindChildByID(hWnd, 1002)
    local edit = reaper.JS_Window_FindChildByID(combo, 1001)
    local path = reaper.JS_Window_GetTitle(edit, "", 1024)
    
    for i = 0, sel_count - 1 do
        local filename = reaper.JS_ListView_GetItemText(file_LV, i, 0)
        local filepath = path .. "/" .. filename
        reaper.ShowConsoleMsg("Processing: " .. filepath .. "\n")
        
        for code, mapping in pairs(ucs_mapping) do
            if filename:match(code) then
                reaper.ShowConsoleMsg("Found match: " .. code .. "\n")
                local source = reaper.PCM_Source_CreateFromFile(filepath)
                if source then
                    reaper.BR_SetMediaSourceProperties(source, {
                        ["CATEGORY"] = mapping.category,
                        ["SUBCATEGORY"] = mapping.subcategory,
                        ["CatID"] = code
                    })
                    reaper.ShowConsoleMsg("Updated metadata for: " .. filename .. "\n")
                end
                break
            end
        end
    end
end